ereport: Task faulted/panicked (#2341)
Depends on #2313, #2350, #2358
Fixes #2309 

It's currently somewhat difficult to become aware of Hubris task panics
and other task faults in a production environment. While MGS can ask the
SP to list task dumps as part of the API for reading dumps, this
requires that the control plane (or faux-mgs user) proactively ask the
SP whether it has any record of panicked tasks, rather than recording
panics as they occur. Therefore, we should have a proactive notification
from the SP indicating that task faults have occurred.

This commit adds code to `packrat` for producing an ereport when a task
has faulted. This could eventually be used by the control plane to
trigger dump collection and produce a service bundle. In addition, it
will provide a more permanent record that a task faulted at a particular
time, even if the SP that contains the faulted task is later reset or
replaced with an entirely different SP. This works using an approach
similar to the one described by @cbiffle in [this comment][1]. There's a
detailed description of how this works [in the module-level RustDoc for
`ereport.rs` in Packrat][2].

The ereports that come out of this thing look like this:

```console
eliza@hekate ~/Code/oxide/hubris $ faux-mgs --interface eno1np0 --discovery-addr '[fe80::0c1d:deff:fef0:d922]:11111' ereports
Jan 15 10:27:41.370 INFO creating SP handle on interface eno1np0, component: faux-mgs
Jan 15 10:27:41.372 INFO initial discovery complete, addr: [fe80::c1d:deff:fef0:d922%2]:11111, interface: eno1np0, socket: control-plane-agent, component: faux-mgs
restart ID: 4e54b7f1-e13a-d9bb-709a-c7e863d64a64
restart IDs did not match (requested 00000000-0000-0000-0000-000000000000)
count: 4

ereports:
0x1: {
    "ereport_message_version": Number(0),
    "hubris_task_gen": Number(0),
    "hubris_task_name": String("packrat"),
    "hubris_uptime_ms": Number(0),
    "lost": Null,
}

0x2: {
    "ereport_message_version": Number(0),
    "hubris_task_gen": Number(0),
    "hubris_task_name": String("ereportulator"),
    "hubris_uptime_ms": Number(378010),
    "k": String("hubris.fault.panic"),
    "msg": String("panicked at task/ereportulator/src/main.rs:158:9:\nim dead lol"),
    "v": Number(0),
}

0x3: {
    "by": Object {
        "gen": Number(0),
        "task": String("jefe"),
    },
    "ereport_message_version": Number(0),
    "hubris_task_gen": Number(0),
    "hubris_task_name": String("user_leds"),
    "hubris_uptime_ms": Number(382914),
    "k": String("hubris.fault.injected"),
    "v": Number(0),
}

0x4: {
    "by": Object {
        "gen": Number(0),
        "task": String("jefe"),
    },
    "ereport_message_version": Number(0),
    "hubris_task_gen": Number(1),
    "hubris_task_name": String("ereportulator"),
    "hubris_uptime_ms": Number(388215),
    "k": String("hubris.fault.injected"),
    "v": Number(0),
}
```


[1]:
  https://github.com/oxidecomputer/hubris/issues/2309#issuecomment-3607491107
[2]:
  https://github.com/oxidecomputer/hubris/blob/1e2b121fcd165dcdbcbdfdc69c36d35520dfa954/task/packrat/src/ereport.rs#L15-L95